[platformio]
name = PORTON_TAREA6

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
; upload_port = COM5   ; descomenta para grabar en hardware real
; monitor_port = COM5
lib_deps =
  knolleary/PubSubClient@^2.8
  adafruit/Adafruit GFX Library@^1.11.9
  adafruit/Adafruit SSD1306@^2.5.9
build_flags =
  -DCORE_DEBUG_LEVEL=0
