[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient@^2.8

; ===== Hardware real (sube por COM5) =====
[env:esp32]
upload_speed = 921600
upload_port = COM5

; ===== Simulación Wokwi (VS Code) =====
[env:wokwi]
build_flags =
    -D SIMULACION
